name:  edgex-device-rfid-llrp
base: core20
adopt-info: metadata
license: Apache-2.0

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: edinburgh
# 2: fuji
# 3: geneva, hanoi
# 4: ireland, jakarta
epoch: 4

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: [$SNAP_DATA/device-rfid-llrp]

apps:
  auto-configure:
    adapter: none
    command-chain:
        - snap/command-chain/snapcraft-runner
    command: bin/auto-configure.sh
    plugs:
      - network
      - network-observe
      - network-control

  device-rfid-llrp:
    adapter: full
    command: bin/device-rfid-llrp $CONFIG_PRO_ARG $CONF_ARG $REGISTRY_ARG
    command-chain:
      - bin/startup-env-var.sh
    environment:
      CONFIG_PRO_ARG: "--cp=consul://localhost:8500"
      CONF_ARG: "--confdir=$SNAP_DATA/config/device-rfid-llrp/res"
      REGISTRY_ARG: "--registry"
      DEVICE_PROFILESDIR: "$SNAP_DATA/config/device-rfid-llrp/res/profiles"
      DEVICE_DEVICESDIR: "$SNAP_DATA/config/device-rfid-llrp/res/devices"
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-rfid-llrp/secrets-token.json
      APPCUSTOM_PROVISION_WATCHER_FOLDER: $SNAP_DATA/config/device-rfid-llrp/res/provision_watchers
    daemon: simple
    passthrough:
      install-mode: disable
    plugs: [network, network-bind]

plugs:
  device-config:
    interface: content 
    target: $SNAP_DATA/config/device-rfid-llrp

parts:
   hooks:
    source: snap/local/hooks
    plugin: make
    build-snaps:
      - go/1.17/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./cmd/configure/configure "$SNAPCRAFT_PART_INSTALL/snap/hooks/configure"
      install -DT ./cmd/install/install "$SNAPCRAFT_PART_INSTALL/snap/hooks/install"

  device-rfid-llrp:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, pkg-config]
    stage-packages: [libzmq5]
    build-snaps:
      - go/1.17/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      # the version is needed for the build
      cat ./VERSION

      make tidy
      make build

      # copy device-rfid-llrp
      install -DT "./cmd/device-rfid-llrp" "$SNAPCRAFT_PART_INSTALL/bin/device-rfid-llrp"

      install -d "$SNAPCRAFT_PART_INSTALL/config/device-rfid-llrp/res/"
      install -DT "./cmd/res/configuration.toml" \
        "$SNAPCRAFT_PART_INSTALL/config/device-rfid-llrp/res/configuration.toml"

      install -d "$SNAPCRAFT_PART_INSTALL/config/device-rfid-llrp/res/profiles/"
      for fpath in ./cmd/res/profiles/*.yaml; do
          fname=$(basename "$fpath")
          install -DT "./cmd/res/profiles/${fname}" \
            "$SNAPCRAFT_PART_INSTALL/config/device-rfid-llrp/res/profiles/${fname}"
      done

      install -d "$SNAPCRAFT_PART_INSTALL/config/device-rfid-llrp/res/provision_watchers/"
      for fpath in ./cmd/res/provision_watchers/*.json; do
          fname=$(basename "$fpath")
          install -DT "./cmd/res/provision_watchers/${fname}" \
            "$SNAPCRAFT_PART_INSTALL/config/device-rfid-llrp/res/provision_watchers/${fname}"
      done

      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-rfid-llrp/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-rfid-llrp/LICENSE"

  runtime-helpers:
    plugin: dump
    source: snap/local/runtime-helpers

  metadata:
    plugin: nil
    source: https://github.com/canonical/edgex-snap-metadata.git
    source-branch: appstream
    source-depth: 1
    override-build: |
      # install the icon at the default internal path
      install -DT edgex-snap-icon.png \
        $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png      
      # change to this project's repo to get the version
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION
      # set the version of this snap
      snapcraftctl set-version $VERSION
    parse-info: [edgex-device-rfid-llrp.md]

 
  auto-configure:
    source: snap/local
    plugin: nil
    stage-packages:
      - curl