name:  edgex-device-rfid-llrp
base: core20
adopt-info: metadata
license: Apache-2.0

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: edinburgh
# 2: fuji
# 3: geneva, hanoi
# 4: ireland, jakarta
epoch: 4

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: [$SNAP_DATA/device-rfid-llrp]

apps:
  auto-configure:
    adapter: none
    command: bin/auto-configure.sh
    command-chain:
      - snap/command-chain/snapcraft-runner 
    plugs:
      - network
      - network-observe # required for /operstate
      - network-control # required for "ip" 

  device-rfid-llrp:
    adapter: full
    command: bin/device-rfid-llrp $CONFIG_PRO_ARG $CONF_ARG $REGISTRY_ARG
    command-chain:
      - bin/startup-env-var.sh
    environment:
      CONFIG_PRO_ARG: "--cp=consul://localhost:8500"
      CONF_ARG: "--confdir=$SNAP_DATA/config/device-rfid-llrp/res"
      REGISTRY_ARG: "--registry"
      DEVICE_PROFILESDIR: "$SNAP_DATA/config/device-rfid-llrp/res/profiles"
      DEVICE_DEVICESDIR: "$SNAP_DATA/config/device-rfid-llrp/res/devices"
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-rfid-llrp/secrets-token.json
      APPCUSTOM_PROVISIONWATCHERDIR: $SNAP_DATA/config/device-rfid-llrp/res/provision_watchers
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

plugs:
  device-config:
    interface: content 
    target: $SNAP_DATA/config/device-rfid-llrp

parts:
  hooks:
    source: snap/local/hooks
    plugin: make
    build-snaps:
      - go/1.18/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./cmd/configure/configure "$SNAPCRAFT_PART_INSTALL/snap/hooks/configure"
      install -DT ./cmd/install/install "$SNAPCRAFT_PART_INSTALL/snap/hooks/install"

  device-rfid-llrp:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, pkg-config]
    stage-packages: [libzmq5]
    build-snaps:
      - go/1.18/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      # the version is needed for the build
      cat ./VERSION

      make tidy
      make build

      install -DT ./cmd/device-rfid-llrp "$SNAPCRAFT_PART_INSTALL/bin/device-rfid-llrp"
      install -DT ./Attribution.txt "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-rfid-llrp/Attribution.txt"
      install -DT ./LICENSE "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-rfid-llrp/LICENSE"

      LLRP_RES_DIR="$SNAPCRAFT_PART_INSTALL/config/device-rfid-llrp/res/"
      mkdir -p "$LLRP_RES_DIR/profiles"
      mkdir -p "$LLRP_RES_DIR/devices"
      mkdir -p "$LLRP_RES_DIR/provision_watchers"
      cp ./cmd/res/configuration.toml "$LLRP_RES_DIR/"
      cp ./cmd/res/profiles/*.yaml "$LLRP_RES_DIR/profiles/"
      cp ./cmd/res/provision_watchers/*.json "$LLRP_RES_DIR/provision_watchers/"


  runtime-helpers:
    plugin: dump
    source: snap/local/runtime-helpers

  metadata:
    plugin: nil
    source: https://github.com/canonical/edgex-snap-metadata.git
    source-branch: appstream
    source-depth: 1
    override-build: |
      # install the icon at the default internal path
      install -DT edgex-snap-icon.png \
        $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png      
      # change to this project's repo to get the version
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION
      # set the version of this snap
      snapcraftctl set-version $VERSION
    parse-info: [edgex-device-rfid-llrp.metainfo.xml]

 
  # copy auto-configure.sh to /bin and make sure curl is installed
  auto-configure:
    plugin: dump
    source: bin/
    organize:
      auto-configure.sh: bin/auto-configure.sh
    stage-packages:
      - curl
