name: edgex-device-rfid-llrp
base: core20
license: Apache-2.0
summary: EdgeX RFID LLRP Device Service
description: Refer to https://snapcraft.io/edgex-device-rfid-llrp
adopt-info: device-rfid-llrp

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: edinburgh
# 2: fuji
# 3: geneva, hanoi
# 4: ireland, jakarta
epoch: 4

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: [$SNAP_DATA/device-rfid-llrp]

plugs:
  device-rfid-llrp-config:
    interface: content
    target: $SNAP_DATA/config/device-rfid-llrp

  # deprecated
  device-config:
    interface: content 
    target: $SNAP_DATA/config/device-rfid-llrp

apps:
  auto-configure:
    adapter: none
    command: bin/auto-configure.sh
    command-chain:
      - snap/command-chain/snapcraft-runner 
    plugs:
      - network
      - network-observe # required for /operstate
      - network-control # required for "ip" 

  device-rfid-llrp:
    adapter: full
    command: bin/device-rfid-llrp --configDir $SNAP_DATA/config/device-rfid-llrp/res --configProvider --registry
    command-chain:
      - bin/source-env-file.sh
    environment:
      DEVICE_PROFILESDIR: $SNAP_DATA/config/device-rfid-llrp/res/profiles
      DEVICE_DEVICESDIR: $SNAP_DATA/config/device-rfid-llrp/res/devices
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-rfid-llrp/secrets-token.json
      APPCUSTOM_PROVISIONWATCHERDIR: $SNAP_DATA/config/device-rfid-llrp/res/provision_watchers
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./helper-go $SNAPCRAFT_PART_INSTALL/bin/helper-go

  device-rfid-llrp:
    source: .
    plugin: make
    build-packages:
      - git
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi

      # set the version of the snap
      snapcraftctl set-version $VERSION
      
      # write version to file for the build
      echo $VERSION > VERSION

      make build
      install -DT ./cmd/device-rfid-llrp "$SNAPCRAFT_PART_INSTALL/bin/device-rfid-llrp"

      RES=$SNAPCRAFT_PART_INSTALL/config/device-rfid-llrp/res/
      mkdir -p $RES
      cp    cmd/res/configuration.yaml $RES
      cp -r cmd/res/profiles $RES
      cp -r cmd/res/provision_watchers $RES
      
      DOC=$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-rfid-llrp
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE

  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh

  # copy auto-configure.sh to /bin and make sure curl is installed
  auto-configure:
    plugin: dump
    source: bin/
    organize:
      auto-configure.sh: bin/auto-configure.sh
    stage-packages:
      - curl
