//
// Copyright (C) 2020 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "generate_param_code.py -i messages.yaml -t binary_test.go -m generated_marshal.go -u generated_unmarshal.go -e generated_encoder.go"; DO NOT EDIT.
package llrp

import (
	"bytes"
)

// b2b converts a bool to a byte, because Go doesn't have a built-in for it.
func b2b(b bool) byte {
	if b {
		return 1
	}
	return 0
}

// MarshalBinary Message 46, GetSupportedVersion.
func (m *GetSupportedVersion) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 56, GetSupportedVersionResponse.
func (m *GetSupportedVersionResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 47, SetProtocolVersion.
func (m *SetProtocolVersion) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 57, SetProtocolVersionResponse.
func (m *SetProtocolVersionResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 1, GetReaderCapabilities.
func (m *GetReaderCapabilities) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	for i := range m.Custom {
		if err := encodeParams(&b, m.Custom[i].getHeader()); err != nil {
			return nil, err
		}
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 11, GetReaderCapabilitiesResponse.
func (m *GetReaderCapabilitiesResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	if m.GeneralDeviceCapabilities != nil {
		if err := encodeParams(&b, m.GeneralDeviceCapabilities.getHeader()); err != nil {
			return nil, err
		}
	}
	if m.LLRPCapabilities != nil {
		if err := encodeParams(&b, m.LLRPCapabilities.getHeader()); err != nil {
			return nil, err
		}
	}
	if m.RegulatoryCapabilities != nil {
		if err := encodeParams(&b, m.RegulatoryCapabilities.getHeader()); err != nil {
			return nil, err
		}
	}
	if m.C1G2LLRPCapabilities != nil {
		if err := encodeParams(&b, m.C1G2LLRPCapabilities.getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.Custom {
		if err := encodeParams(&b, m.Custom[i].getHeader()); err != nil {
			return nil, err
		}
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 20, AddROSpec.
func (m *AddROSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.ROSpec.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 30, AddROSpecResponse.
func (m *AddROSpecResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 21, DeleteROSpec.
func (m *DeleteROSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 31, DeleteROSpecResponse.
func (m *DeleteROSpecResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 22, StartROSpec.
func (m *StartROSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 32, StartROSpecResponse.
func (m *StartROSpecResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 23, StopROSpec.
func (m *StopROSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 33, StopROSpecResponse.
func (m *StopROSpecResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 24, EnableROSpec.
func (m *EnableROSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 34, EnableROSpecResponse.
func (m *EnableROSpecResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 25, DisableROSpec.
func (m *DisableROSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 35, DisableROSpecResponse.
func (m *DisableROSpecResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 26, GetROSpecs.
func (m *GetROSpecs) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 36, GetROSpecsResponse.
func (m *GetROSpecsResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	for i := range m.ROSpecs {
		if err := encodeParams(&b, m.ROSpecs[i].getHeader()); err != nil {
			return nil, err
		}
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 40, AddAccessSpec.
func (m *AddAccessSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.AccessSpec.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 50, AddAccessSpecResponse.
func (m *AddAccessSpecResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 41, DeleteAccessSpec.
func (m *DeleteAccessSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 51, DeleteAccessSpecResponse.
func (m *DeleteAccessSpecResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 42, EnableAccessSpec.
func (m *EnableAccessSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 52, EnableAccessSpecResponse.
func (m *EnableAccessSpecResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 43, DisableAccessSpec.
func (m *DisableAccessSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 53, DisableAccessSpecResponse.
func (m *DisableAccessSpecResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 44, GetAccessSpecs.
func (m *GetAccessSpecs) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 54, GetAccessSpecsResponse.
func (m *GetAccessSpecsResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	for i := range m.AccessSpecs {
		if err := encodeParams(&b, m.AccessSpecs[i].getHeader()); err != nil {
			return nil, err
		}
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 45, ClientRequestOp.
func (m *ClientRequestOp) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.TagReportData.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 55, ClientRequestOpResponse.
func (m *ClientRequestOpResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.ClientRequestResponse.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 60, GetReport.
func (m *GetReport) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 61, ROAccessReport.
func (m *ROAccessReport) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	for i := range m.TagReportData {
		if err := encodeParams(&b, m.TagReportData[i].getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.RFSurveyReportData {
		if err := encodeParams(&b, m.RFSurveyReportData[i].getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.Custom {
		if err := encodeParams(&b, m.Custom[i].getHeader()); err != nil {
			return nil, err
		}
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 62, KeepAlive.
func (m *KeepAlive) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 72, KeepAliveAck.
func (m *KeepAliveAck) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 63, ReaderEventNotification.
func (m *ReaderEventNotification) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.ReaderEventNotificationData.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 64, EnableEventsAndReports.
func (m *EnableEventsAndReports) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 100, ErrorMessage.
func (m *ErrorMessage) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 2, GetReaderConfig.
func (m *GetReaderConfig) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	for i := range m.Custom {
		if err := encodeParams(&b, m.Custom[i].getHeader()); err != nil {
			return nil, err
		}
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 12, GetReaderConfigResponse.
func (m *GetReaderConfigResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	if m.Identification != nil {
		if err := encodeParams(&b, m.Identification.getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.AntennaProperties {
		if err := encodeParams(&b, m.AntennaProperties[i].getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.AntennaConfigurations {
		if err := encodeParams(&b, m.AntennaConfigurations[i].getHeader()); err != nil {
			return nil, err
		}
	}
	if m.ReaderEventNotificationSpec != nil {
		if err := encodeParams(&b, m.ReaderEventNotificationSpec.getHeader()); err != nil {
			return nil, err
		}
	}
	if m.ROReportSpec != nil {
		if err := encodeParams(&b, m.ROReportSpec.getHeader()); err != nil {
			return nil, err
		}
	}
	if m.AccessReportSpec != nil {
		if err := encodeParams(&b, m.AccessReportSpec.getHeader()); err != nil {
			return nil, err
		}
	}
	if m.LLRPConfigurationStateValue != nil {
		if err := encodeParams(&b, m.LLRPConfigurationStateValue.getHeader()); err != nil {
			return nil, err
		}
	}
	if m.KeepAliveSpec != nil {
		if err := encodeParams(&b, m.KeepAliveSpec.getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.GPIPortCurrentStates {
		if err := encodeParams(&b, m.GPIPortCurrentStates[i].getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.GPOWriteData {
		if err := encodeParams(&b, m.GPOWriteData[i].getHeader()); err != nil {
			return nil, err
		}
	}
	if m.EventsAndReports != nil {
		if err := encodeParams(&b, m.EventsAndReports.getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.Custom {
		if err := encodeParams(&b, m.Custom[i].getHeader()); err != nil {
			return nil, err
		}
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 3, SetReaderConfig.
func (m *SetReaderConfig) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if m.ReaderEventNotificationSpec != nil {
		if err := encodeParams(&b, m.ReaderEventNotificationSpec.getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.AntennaProperties {
		if err := encodeParams(&b, m.AntennaProperties[i].getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.AntennaConfigurations {
		if err := encodeParams(&b, m.AntennaConfigurations[i].getHeader()); err != nil {
			return nil, err
		}
	}
	if m.ROReportSpec != nil {
		if err := encodeParams(&b, m.ROReportSpec.getHeader()); err != nil {
			return nil, err
		}
	}
	if m.AccessReportSpec != nil {
		if err := encodeParams(&b, m.AccessReportSpec.getHeader()); err != nil {
			return nil, err
		}
	}
	if m.KeepAliveSpec != nil {
		if err := encodeParams(&b, m.KeepAliveSpec.getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.GPOWriteData {
		if err := encodeParams(&b, m.GPOWriteData[i].getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.GPIPortCurrentStates {
		if err := encodeParams(&b, m.GPIPortCurrentStates[i].getHeader()); err != nil {
			return nil, err
		}
	}
	if m.EventsAndReports != nil {
		if err := encodeParams(&b, m.EventsAndReports.getHeader()); err != nil {
			return nil, err
		}
	}
	for i := range m.Custom {
		if err := encodeParams(&b, m.Custom[i].getHeader()); err != nil {
			return nil, err
		}
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 13, SetReaderConfigResponse.
func (m *SetReaderConfigResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 14, CloseConnection.
func (m *CloseConnection) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 4, CloseConnectionResponse.
func (m *CloseConnectionResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	if err := encodeParams(&b, m.LLRPStatus.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Message 1023, CustomMessage.
func (m *CustomMessage) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := m.EncodeFields(&b); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// MarshalBinary Parameter 1, AntennaID.
func (p *AntennaID) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 2, FirstSeenUTC.
func (p *FirstSeenUTC) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 3, FirstSeenUptime.
func (p *FirstSeenUptime) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 4, LastSeenUTC.
func (p *LastSeenUTC) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 5, LastSeenUptime.
func (p *LastSeenUptime) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 6, PeakRSSI.
func (p *PeakRSSI) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 7, ChannelIndex.
func (p *ChannelIndex) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 8, TagSeenCount.
func (p *TagSeenCount) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 9, ROSpecID.
func (p *ROSpecID) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 10, InventoryParameterSpecID.
func (p *InventoryParameterSpecID) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 11, C1G2CRC.
func (p *C1G2CRC) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 12, C1G2PC.
func (p *C1G2PC) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 13, EPC96.
func (p *EPC96) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 14, SpecIndex.
func (p *SpecIndex) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 15, ClientRequestOpSpecResult.
func (p *ClientRequestOpSpecResult) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 16, AccessSpecID.
func (p *AccessSpecID) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 17, OpSpecID.
func (p *OpSpecID) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 18, C1G2SingulationDetails.
func (p *C1G2SingulationDetails) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 19, C1G2XPCW1.
func (p *C1G2XPCW1) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 20, C1G2XPCW2.
func (p *C1G2XPCW2) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[1:], nil
}

// MarshalBinary Parameter 128, UTCTimestamp.
func (p *UTCTimestamp) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 129, Uptime.
func (p *Uptime) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 137, GeneralDeviceCapabilities.
func (p *GeneralDeviceCapabilities) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 139, ReceiveSensitivityTableEntry.
func (p *ReceiveSensitivityTableEntry) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 140, PerAntennaAirProtocol.
func (p *PerAntennaAirProtocol) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 141, GPIOCapabilities.
func (p *GPIOCapabilities) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 142, LLRPCapabilities.
func (p *LLRPCapabilities) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 143, RegulatoryCapabilities.
func (p *RegulatoryCapabilities) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 144, UHFBandCapabilities.
func (p *UHFBandCapabilities) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 145, TransmitPowerLevelTableEntry.
func (p *TransmitPowerLevelTableEntry) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 146, FrequencyInformation.
func (p *FrequencyInformation) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 147, FrequencyHopTable.
func (p *FrequencyHopTable) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 148, FixedFrequencyTable.
func (p *FixedFrequencyTable) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 149, PerAntennaReceiveSensitivityRange.
func (p *PerAntennaReceiveSensitivityRange) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 177, ROSpec.
func (p *ROSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 178, ROBoundarySpec.
func (p *ROBoundarySpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 179, ROSpecStartTrigger.
func (p *ROSpecStartTrigger) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 180, PeriodicTriggerValue.
func (p *PeriodicTriggerValue) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 181, GPITriggerValue.
func (p *GPITriggerValue) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 182, ROSpecStopTrigger.
func (p *ROSpecStopTrigger) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 183, AISpec.
func (p *AISpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 184, AISpecStopTrigger.
func (p *AISpecStopTrigger) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 185, TagObservationTrigger.
func (p *TagObservationTrigger) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 186, InventoryParameterSpec.
func (p *InventoryParameterSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 187, RFSurveySpec.
func (p *RFSurveySpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 188, RFSurveySpecStopTrigger.
func (p *RFSurveySpecStopTrigger) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 207, AccessSpec.
func (p *AccessSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 208, AccessSpecStopTrigger.
func (p *AccessSpecStopTrigger) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 209, AccessCommand.
func (p *AccessCommand) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 210, ClientRequestOpSpec.
func (p *ClientRequestOpSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 211, ClientRequestResponse.
func (p *ClientRequestResponse) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 217, LLRPConfigurationStateValue.
func (p *LLRPConfigurationStateValue) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 218, Identification.
func (p *Identification) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 219, GPOWriteData.
func (p *GPOWriteData) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 220, KeepAliveSpec.
func (p *KeepAliveSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 221, AntennaProperties.
func (p *AntennaProperties) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 222, AntennaConfiguration.
func (p *AntennaConfiguration) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 223, RFReceiver.
func (p *RFReceiver) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 224, RFTransmitter.
func (p *RFTransmitter) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 225, GPIPortCurrentState.
func (p *GPIPortCurrentState) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 226, EventsAndReports.
func (p *EventsAndReports) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 237, ROReportSpec.
func (p *ROReportSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 238, TagReportContentSelector.
func (p *TagReportContentSelector) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 239, AccessReportSpec.
func (p *AccessReportSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 240, TagReportData.
func (p *TagReportData) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 241, EPCData.
func (p *EPCData) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 242, RFSurveyReportData.
func (p *RFSurveyReportData) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 243, FrequencyRSSILevelEntry.
func (p *FrequencyRSSILevelEntry) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 244, ReaderEventNotificationSpec.
func (p *ReaderEventNotificationSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 245, EventNotificationState.
func (p *EventNotificationState) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 246, ReaderEventNotificationData.
func (p *ReaderEventNotificationData) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 247, HoppingEvent.
func (p *HoppingEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 248, GPIEvent.
func (p *GPIEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 249, ROSpecEvent.
func (p *ROSpecEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 250, ReportBufferLevelWarningEvent.
func (p *ReportBufferLevelWarningEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 251, ReportBufferOverflowErrorEvent.
func (p *ReportBufferOverflowErrorEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 252, ReaderExceptionEvent.
func (p *ReaderExceptionEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 253, RFSurveyEvent.
func (p *RFSurveyEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 254, AISpecEvent.
func (p *AISpecEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 255, AntennaEvent.
func (p *AntennaEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 256, ConnectionAttemptEvent.
func (p *ConnectionAttemptEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 257, ConnectionCloseEvent.
func (p *ConnectionCloseEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 287, LLRPStatus.
func (p *LLRPStatus) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 288, FieldError.
func (p *FieldError) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 289, ParameterError.
func (p *ParameterError) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 327, C1G2LLRPCapabilities.
func (p *C1G2LLRPCapabilities) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 328, UHFC1G2RFModeTable.
func (p *UHFC1G2RFModeTable) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 329, UHFC1G2RFModeTableEntry.
func (p *UHFC1G2RFModeTableEntry) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 330, C1G2InventoryCommand.
func (p *C1G2InventoryCommand) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 331, C1G2Filter.
func (p *C1G2Filter) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 332, C1G2TagInventoryMask.
func (p *C1G2TagInventoryMask) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 333, C1G2TagInventoryStateAwareFilterAction.
func (p *C1G2TagInventoryStateAwareFilterAction) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 334, C1G2TagInventoryStateUnawareFilterAction.
func (p *C1G2TagInventoryStateUnawareFilterAction) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 335, C1G2RFControl.
func (p *C1G2RFControl) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 336, C1G2SingulationControl.
func (p *C1G2SingulationControl) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 337, C1G2TagInventoryStateAwareSingulationAction.
func (p *C1G2TagInventoryStateAwareSingulationAction) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 338, C1G2TagSpec.
func (p *C1G2TagSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 339, C1G2TargetTag.
func (p *C1G2TargetTag) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 341, C1G2Read.
func (p *C1G2Read) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 342, C1G2Write.
func (p *C1G2Write) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 343, C1G2Kill.
func (p *C1G2Kill) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 344, C1G2Lock.
func (p *C1G2Lock) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 345, C1G2LockPayload.
func (p *C1G2LockPayload) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 346, C1G2BlockErase.
func (p *C1G2BlockErase) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 347, C1G2BlockWrite.
func (p *C1G2BlockWrite) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 348, C1G2EPCMemorySelector.
func (p *C1G2EPCMemorySelector) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 349, C1G2ReadOpSpecResult.
func (p *C1G2ReadOpSpecResult) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 350, C1G2WriteOpSpecResult.
func (p *C1G2WriteOpSpecResult) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 351, C1G2KillOpSpecResult.
func (p *C1G2KillOpSpecResult) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 352, C1G2LockOpSpecResult.
func (p *C1G2LockOpSpecResult) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 353, C1G2BlockEraseOpSpecResult.
func (p *C1G2BlockEraseOpSpecResult) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 354, C1G2BlockWriteOpSpecResult.
func (p *C1G2BlockWriteOpSpecResult) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 355, LoopSpec.
func (p *LoopSpec) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 356, SpecLoopEvent.
func (p *SpecLoopEvent) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 357, C1G2Recommission.
func (p *C1G2Recommission) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 358, C1G2BlockPermalock.
func (p *C1G2BlockPermalock) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 359, C1G2GetBlockPermalockStatus.
func (p *C1G2GetBlockPermalockStatus) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 360, C1G2RecommissionOpSpecResult.
func (p *C1G2RecommissionOpSpecResult) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 361, C1G2BlockPermalockOpSpecResult.
func (p *C1G2BlockPermalockOpSpecResult) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 362, C1G2GetBlockPermalockStatusOpSpecResult.
func (p *C1G2GetBlockPermalockStatusOpSpecResult) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 363, MaximumReceiveSensitivity.
func (p *MaximumReceiveSensitivity) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 365, RFSurveyFrequencyCapabilities.
func (p *RFSurveyFrequencyCapabilities) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}

// MarshalBinary Parameter 1023, Custom.
func (p *Custom) MarshalBinary() ([]byte, error) {
	b := bytes.Buffer{}
	if err := encodeParams(&b, p.getHeader()); err != nil {
		return nil, err
	}
	return b.Bytes()[4:], nil
}
