//
// Copyright (C) 2020 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=ParamType,connAttemptEventParam"; DO NOT EDIT.

package llrp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParamLLRPStatus-287]
	_ = x[ParamFieldError-288]
	_ = x[ParamParameterError-289]
	_ = x[ParamReaderEventNotificationData-246]
	_ = x[ParamUTCTimestamp-128]
	_ = x[ParamUptime-129]
	_ = x[ParamHoppingEvent-247]
	_ = x[ParamGPIEvent-248]
	_ = x[ParamROSpecEvent-249]
	_ = x[ParamBufferLevelWarnEvent-250]
	_ = x[ParamBufferOverflowEvent-251]
	_ = x[ParamReaderExceptionEvent-252]
	_ = x[ParamRFSurveyEvent-253]
	_ = x[ParamAISpecEvent-254]
	_ = x[ParamAntennaEvent-255]
	_ = x[ParamConnectionAttemptEvent-256]
	_ = x[ParamConnectionCloseEvent-257]
	_ = x[ParamSpecLoopEvent-365]
	_ = x[ParamCustomParameter-1023]
	_ = x[ParamEPC96-13]
	_ = x[ParamROSpectID-9]
	_ = x[ParamSpecIndex-14]
	_ = x[ParamInventoryParamSpecID-10]
	_ = x[ParamAntennaID-1]
	_ = x[ParamPeakRSSI-6]
	_ = x[ParamChannelIndex-7]
	_ = x[ParamFirstSeenUTC-2]
	_ = x[ParamFirstSeenUptime-3]
	_ = x[ParamLastSeenUTC-4]
	_ = x[ParamLastSeenUptime-5]
	_ = x[ParamTagSeenCount-8]
	_ = x[ParamClientReqOpSpecResult-15]
	_ = x[ParamAccessSpecID-16]
	_ = x[ParamOpSpecID-17]
	_ = x[ParamC1G2PC-12]
	_ = x[ParamC1G2XPCW1-19]
	_ = x[ParamC1G2XPCW2-20]
	_ = x[ParamC1G2CRC-11]
	_ = x[ParamC1G2SingulationDetails-18]
	_ = x[paramInvalid-0]
}

const (
	_ParamType_name_0 = "paramInvalidParamAntennaIDParamFirstSeenUTCParamFirstSeenUptimeParamLastSeenUTCParamLastSeenUptimeParamPeakRSSIParamChannelIndexParamTagSeenCountParamROSpectIDParamInventoryParamSpecIDParamC1G2CRCParamC1G2PCParamEPC96ParamSpecIndexParamClientReqOpSpecResultParamAccessSpecIDParamOpSpecIDParamC1G2SingulationDetailsParamC1G2XPCW1ParamC1G2XPCW2"
	_ParamType_name_1 = "ParamUTCTimestampParamUptime"
	_ParamType_name_2 = "ParamReaderEventNotificationDataParamHoppingEventParamGPIEventParamROSpecEventParamBufferLevelWarnEventParamBufferOverflowEventParamReaderExceptionEventParamRFSurveyEventParamAISpecEventParamAntennaEventParamConnectionAttemptEventParamConnectionCloseEvent"
	_ParamType_name_3 = "ParamLLRPStatusParamFieldErrorParamParameterError"
	_ParamType_name_4 = "ParamSpecLoopEvent"
	_ParamType_name_5 = "ParamCustomParameter"
)

var (
	_ParamType_index_0 = [...]uint16{0, 12, 26, 43, 63, 79, 98, 111, 128, 145, 159, 184, 196, 207, 217, 231, 257, 274, 287, 314, 328, 342}
	_ParamType_index_1 = [...]uint8{0, 17, 28}
	_ParamType_index_2 = [...]uint8{0, 32, 49, 62, 78, 103, 127, 152, 170, 186, 203, 230, 255}
	_ParamType_index_3 = [...]uint8{0, 15, 30, 49}
)

func (i ParamType) String() string {
	switch {
	case i <= 20:
		return _ParamType_name_0[_ParamType_index_0[i]:_ParamType_index_0[i+1]]
	case 128 <= i && i <= 129:
		i -= 128
		return _ParamType_name_1[_ParamType_index_1[i]:_ParamType_index_1[i+1]]
	case 246 <= i && i <= 257:
		i -= 246
		return _ParamType_name_2[_ParamType_index_2[i]:_ParamType_index_2[i+1]]
	case 287 <= i && i <= 289:
		i -= 287
		return _ParamType_name_3[_ParamType_index_3[i]:_ParamType_index_3[i+1]]
	case i == 365:
		return _ParamType_name_4
	case i == 1023:
		return _ParamType_name_5
	default:
		return "ParamType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectedSuccessfully-0]
	_ = x[ConnExistsReaderInitiated-1]
	_ = x[ConnExistsClientInitiated-2]
	_ = x[ConnFailedReasonUnknown-3]
	_ = x[ConnAttemptedAgain-4]
}

const _connAttemptEventParam_name = "connectionSuccessreaderInitiatedConnExistsclientInitiatedConnExistsfailedReasonUnknownanotherConnAttempted"

var _connAttemptEventParam_index = [...]uint8{0, 17, 42, 67, 86, 106}

func (cs ConnectionStatus) String() string {
	if cs >= ConnectionStatus(len(_connAttemptEventParam_index)-1) {
		return "connAttemptEventParam(" + strconv.FormatInt(int64(cs), 10) + ")"
	}
	return _connAttemptEventParam_name[_connAttemptEventParam_index[cs]:_connAttemptEventParam_index[cs+1]]
}
