#!/bin/bash -e

# get the values of $SNAP_DATA and $SNAP using the current symlink instead of
# the default behavior which has the revision hard-coded, which breaks after
# a refresh
SNAP_DATA_CURRENT=${SNAP_DATA/%$SNAP_REVISION/current}
SNAP_CURRENT=${SNAP/%$SNAP_REVISION/current}

# Install all the config files from $SNAP/config/SERVICE/res/configuration.toml 
# into $SNAP_DATA/config
mkdir -p "$SNAP_DATA/config"
if [ ! -f "$SNAP_DATA/config/device-rfid-llrp-go/res/configuration.toml" ]; then
    mkdir -p "$SNAP_DATA/config/device-rfid-llrp-go/res"
    mkdir -p "$SNAP_DATA/config/device-rfid-llrp-go/res/provision_watchers"	
    cp "$SNAP/config/device-rfid-llrp-go/res/configuration.toml" "$SNAP_DATA/config/device-rfid-llrp-go/res/configuration.toml"
fi

# Copy the device profiles into $SNAP_DATA
find "$SNAP/config/device-rfid-llrp-go/res/" -maxdepth 1 -iname "*.yaml" -type f \
    -exec cp -u -t "$SNAP_DATA/config/device-rfid-llrp-go/res/" {} \; 

# Also copy provision_watchers device json files into $SNAP_DATA
find "$SNAP/config/device-rfid-llrp-go/res/provision_watchers/" -maxdepth 1 -iname "*.json" -type f \
    -exec cp -u -t "$SNAP_DATA/config/device-rfid-llrp-go/res/provision_watchers/" {} \; 



